# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SimTerra
gm_email: simterra@googlegroups.com
gm_name: SimTerra GMs
description: > # this means to ignore newlines until "baseurl:"
  A post-apocalyptic, fantasy LARP set in an alternate/future Earth centuries
  after modern civilization has crumbled and nature has retaken most of the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.simterra.net" # the base hostname & protocol for your site
facebook_username: Simterra FB Page
docs_url: "https://docs.google.com/document/d/1fOBNu7UqoxkuoiWcn2Wky2ONye2H3IC2Miv5BNqDwgk/edit?usp=sharing"

# Build settings
markdown: kramdown
